### ISSUE TITLE
threshold 配置项无效

### ISSUE THREAD

**Issue by Jaciky** [anncwb/vite-plugin-compression#1]
threshold 配置项无效
版本0.2.2

**Comment by anncwb** [comment]
能给我复现？ 是怎么无效，我这边测试可以

**Comment by anncwb** [comment]
可能是我文档写错了，单位是 b不是kb

**Comment by Jaciky** [comment]
嗯嗯 我测试了 是这样的。 也怪我没有多测试，多谢了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "anncwb/vite-plugin-compression"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月2日(星期二) 上午9:49
收件人:&nbsp;"anncwb/vite-plugin-compression"<vite-plugin-compression@noreply.github.com&gt;;
抄送:&nbsp;"Jaciky"<1104670232@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [anncwb/vite-plugin-compression] threshold 配置项无效 (#1)





 
可能是我文档写错了，单位是 b不是kb

**Comment by anncwb** [comment]
我单位写错更新了
