### ISSUE TITLE
Vite Manifest.json points to the normal .js file not the .js.gz file.

### ISSUE THREAD

**Issue by svondervoort** [anncwb/vite-plugin-compression#16]
I'm not sure if I understand this plugin correctly, but I notice that it generates additional `.js.gz` versions of the originals, as opposed to the vite-plugin-compress which compresses the original file. Now this should not be a problem, but how do I make sure the compressed `.gz` file is loaded? Or is this a server thing?

**Comment by julesjanssen** [comment]
This should probably be a server thing. The client usually requests the regular `.js` file, with a header signaling that they understand gzip compression. The server then replies with a gzipped version of the `.js` file.
This plugin just allows you to pre-compress files, so the server doesn't have to compress these files on the fly. See for example the [nginx gzip_static module](https://nginx.org/en/docs/http/ngx_http_gzip_static_module.html).
