### ISSUE TITLE
Why the fork?

### ISSUE THREAD

**Issue by polarathene** [anncwb/vite-plugin-compression#2]
I understand that you've added gzip as an alternative option and added some other changes, but why was there no attempt to upstream to the original project via PR?

Do you plan on supporting output for both gzip and brotli, rather than just a single pre-compressed asset?

---

> a separate copy has been modified and some functions have been added.

If the original project does add gzip support, the differences that this project offers may become more vague to check. Perhaps you should expand on this on the README a bit more?

**Comment by anncwb** [comment]
You can see the extended selection in Options
