### ISSUE TITLE
outDir为绝对路径时,无法正确解析路径

### ISSUE THREAD

**Issue by 823239259** [anncwb/vite-plugin-compression#6]
如果outDir采用绝对路径的方式时, 
![image](https://user-images.githubusercontent.com/26101366/126134097-71d67511-b671-414e-a396-ecaa27945e92.png)

outputPath = _path2.default.join(config.root, config.build.outDir); 无法正常解析到文件路径

![image](https://user-images.githubusercontent.com/26101366/126134249-30afce47-b670-4648-a7bb-3d1bd12f485f.png)

**Comment by swlws** [comment]
![image](https://user-images.githubusercontent.com/12153700/126616003-34c167db-7033-4865-b6e4-2432e95f4195.png)

同样的问题，配置为绝对路径时，插件读不到文件

![image](https://user-images.githubusercontent.com/12153700/126616168-064f862d-0211-4fa0-adae-565beee68c44.png)

**Comment by anncwb** [comment]
close 4d7565f1addd97ab3eee88f8a94a4b09ae2d1d17
